export * from "../generated/index.ts";

export const schemaNames = [
  "allowed-inputs",
  "anchors",
  "benchmark-arm-decision-bundle",
  "benchmark-arm-freeze",
  "benchmark-artifact-provenance",
  "benchmark-broker-snapshot",
  "benchmark-custody-state",
  "benchmark-evidence-packet",
  "benchmark-job-event",
  "benchmark-metering-reconciliation",
  "benchmark-pc-decision",
  "benchmark-provider-usage",
  "benchmark-replacement-ledger",
  "benchmark-runtime-settings",
  "benchmark-sac-calibration-bundle",
  "benchmark-source-universe",
  "benchmark-sterile-root-capability",
  "calibration-followup-v2",
  "calibration-official-review-v2",
  "claim",
  "concern-ledger",
  "concern-resolution",
  "decision",
  "discussion-issue",
  "discussion-position",
  "event-durable-tip-v2",
  "event-envelope-v2",
  "event-envelope",
  "event-semantic-draft-v2",
  "evidence-packet",
  "extraction-fixture-contract",
  "extraction-fixture-manifest",
  "extraction-report",
  "final-review",
  "followup",
  "freeze-record",
  "identity",
  "invocation-result",
  "literature-registry",
  "math-claim-inventory",
  "math-confirmation-report",
  "math-finding-ledger",
  "math-formal-proof-result",
  "math-tool-evidence",
  "math-validation-bundle",
  "meta-review",
  "official-review",
  "paper-dossier",
  "parse-verification-report",
  "persona",
  "phase-state",
  "phase-tasks",
  "question-ledger",
  "rebuttal",
  "response-matrix",
  "role-state",
  "run-budget",
  "run-config",
  "run-state",
  "score-history",
  "submission-manifest",
  "table-asset",
  "task-context",
  "terminal-arm-input",
  "validation-bundle",
  "validation-finding",
  "watchdog-config",
  "watchdog-status",
] as const;

export type SchemaName = (typeof schemaNames)[number];

export function schemaFilename(name: SchemaName): string {
  return `${name}.schema.json`;
}
